version: '3.8'

services:
  mysql:
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3308:3306'
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/
      - ./vendor/:/var/www/html/vendor/
    stdin_open: true
    tty: true
    networks:
      - mynetwork

  server:
    image: nginx:stable-bullseye-perl
    container_name: server
    ports: ['8200:80']
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
