version: '3.8'

services:
  mysql:
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3308:3306'
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - mysql
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - mynetwork

networks:
  mynetwork:
