name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  run-composer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install Composer dependencies
      run: |
        composer install
        composer require --dev phpunit || true

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

  quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip

    - name: Restore Composer cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Run PHP CodeSniffer and PHPStan
      run: |
        set -e
        vendor/bin/phpcs -d memory_limit=512M -s src
        PHP_CS_STATUS=$?
        vendor/bin/phpstan --memory-limit=-1 analyse src
        PHP_STAN_STATUS=$?
        if [ $PHP_CS_STATUS -ne 0 -o $PHP_STAN_STATUS -ne 0 ]; then exit 1; fi
